export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const UPDATE_MESSAGE = "UPDATE_MESSAGE";
export const GET_MESSAGE = "GET_MESSAGE";
export const CURRENT_MESSAGE = "CURRENT_MESSAGE";
